"""Publish the Nudge bot's Foundry encounter records as wiki pages.

Added 2026-09-17. The bot saves every Foundry encounter to
``data/encounters/<code>/<date>-<id>.json`` in its public repo; the same
workflow that publishes the PBP transcripts pulls those and runs this.

⭐ **The bot's records are the source of truth.** Everything under
``topics/Encounters/`` and the whole of ``encounters.tree`` is generated:
a page removed from the records is removed here, and an edit made here is
overwritten. Hand-written encounter pages elsewhere are never touched, and
the duplicate-name guard stops a generated page from ever sharing a name
with one (Writerside would silently publish only one of the two).

Its own Writerside instance, like the transcripts, so generated fights
never crowd the hand-written table of contents.

Idempotent: a run that changes nothing writes nothing.
"""

import argparse
import importlib.util
import json
import sys
from collections import defaultdict
from pathlib import Path
from xml.sax.saxutils import quoteattr

sys.path.insert(0, str(Path(__file__).resolve().parent))
from encounter_render import page_name, render_page, when  # noqa: E402


def _load_guard():
    """pbp_sync's whole-wiki duplicate guard, loaded by path.

    ⚠️ Not by putting pbp_sync on sys.path: it has its own ``render`` and
    ``sync`` modules, and whichever loaded first would shadow the other.
    For the same reason this folder's modules carry ``encounter_`` names.
    """
    path = Path(__file__).resolve().parent.parent / "pbp_sync" / "guards.py"
    spec = importlib.util.spec_from_file_location("pbp_sync_guards", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.assert_no_duplicate_topics


assert_no_duplicate_topics = _load_guard()

START_PAGE = "Encounters.md"
WIKI_ROOT = Path(__file__).resolve().parent.parent.parent
TOPICS_DIR = WIKI_ROOT / "Writerside" / "topics"
OUT_DIR = TOPICS_DIR / "Encounters"
TREE_PATH = WIKI_ROOT / "Writerside" / "encounters.tree"


def load_records(source: Path) -> list[dict]:
    """Every readable record, oldest first. A missing folder means no fights yet, not an error."""
    records = []
    for path in sorted(source.rglob("*.json")) if source.exists() else []:
        try:
            record = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as e:
            print(f"Skipping unreadable record {path.name}: {e}")
            continue
        if isinstance(record, dict) and record.get("code") and record.get("encounter_id"):
            records.append(record)
    return sorted(records, key=lambda r: (str(r.get("started_at") or ""), str(r["encounter_id"])))


def plan(records: list[dict]) -> list[tuple[str, dict]]:
    """(page name, record) pairs. Two fights that would share a name get their id appended."""
    names: dict[str, int] = defaultdict(int)
    for record in records:
        names[page_name(record)] += 1
    return [((page_name(r) if names[page_name(r)] == 1
              else page_name(r)[:-3] + "-" + "".join(c for c in str(r["encounter_id"]) if c.isalnum())[:8] + ".md"), r)
            for r in records]


def render_index(pages: list[tuple[str, dict]]) -> str:
    out = ["# Encounters", "",
           "Every fight run in Foundry with Tongs Browser's encounter sync, newest first, generated from the "
           "Path Wars Nudge bot's records.", ""]
    by_campaign = defaultdict(list)
    for name, record in pages:
        by_campaign[(record["code"], record.get("campaign") or "")].append((name, record))
    if not by_campaign:
        out.append("No encounters yet.")
    for (code, campaign), items in sorted(by_campaign.items()):
        out += [f"## {code} {campaign}".rstrip(), ""]
        for name, record in reversed(items):
            status = "ended" if record.get("ended") else "running"
            out.append(f"- [{record.get('name') or 'Encounter'}]({name}): {when(record.get('started_at'))}, {status}")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def render_tree(pages: list[tuple[str, dict]]) -> str:
    groups = defaultdict(list)
    for name, record in pages:
        groups[(record["code"], record.get("campaign") or "")].append(name)
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<!DOCTYPE instance-profile',
           '        SYSTEM "https://resources.jetbrains.com/writerside/1.0/product-profile.dtd">', "",
           "<!-- GENERATED by scripts/encounter_sync - do not edit by hand. -->", "",
           f'<instance-profile id="encounters" name="Encounters" start-page="{START_PAGE}">',
           f'    <toc-element topic="{START_PAGE}">']
    for (code, campaign), names in sorted(groups.items()):
        out.append(f"        <toc-element toc-title={quoteattr(f'{code} {campaign}'.strip())}>")
        out += [f"            <toc-element topic={quoteattr(n)}/>" for n in reversed(names)]
        out.append("        </toc-element>")
    out += ["    </toc-element>", "</instance-profile>"]
    return "\n".join(out) + "\n"


def _write(path: Path, body: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == body:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return True


def sync(source: Path, out_dir: Path = OUT_DIR, tree_path: Path = TREE_PATH,
         topics_dir: Path = TOPICS_DIR) -> int:
    """Write every page, the index and the tree; remove pages no record backs. Returns files changed."""
    pages = plan(load_records(source))
    changed = sum(_write(out_dir / name, render_page(record)) for name, record in pages)
    changed += _write(out_dir / START_PAGE, render_index(pages))
    expected = {name for name, _ in pages} | {START_PAGE}
    for stale in out_dir.glob("*.md") if out_dir.exists() else []:
        if stale.name not in expected:
            stale.unlink()
            changed += 1
    changed += _write(tree_path, render_tree(pages))
    assert_no_duplicate_topics(topics_dir)
    return changed


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", type=Path, required=True, help="the bot repo's data/encounters")
    args = parser.parse_args(argv)
    print(f"Encounter pages: {sync(args.source)} file(s) changed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
