"""Render ``Writerside/pbp.tree`` — one instance holding every transcript.

A separate Writerside instance, not extra entries in ``mi.tree``. There
are 175 monthly transcripts and counting; dropping them into the main
table of contents would bury the hand-written wiki under three years of
chat logs. An instance gives them their own tab, and leaves the existing
four instances exactly as they were.

Grouped by campaign, newest month first within each campaign — a reader
looking for a transcript almost always wants the recent end.
"""

from collections import defaultdict

_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE instance-profile
        SYSTEM "https://resources.jetbrains.com/writerside/1.0/product-profile.dtd">

<!-- GENERATED by scripts/pbp_sync — do not edit by hand.
     Regenerate with the sync script; see scripts/pbp_sync/README.md. -->

<instance-profile id="pbp"
                  name="Play-by-post transcripts"
                  start-page="{start}">
"""

_FOOTER = "</instance-profile>\n"


def render_tree(jobs, master_index: str, index_for) -> str:
    """Build the instance profile XML from the sync plan.

    ``jobs`` is the list of ``(src, dest_name, code, slug, month)`` tuples
    that ``sync`` is about to publish, so the tree can never list a page
    that was not written — the two come from one plan rather than two
    independent walks of the directory.

    ``master_index`` becomes the start page, and ``index_for(code, slug)``
    supplies each campaign's index page, which becomes the campaign's own
    node with its months nested underneath. Both are REQUIRED arguments
    rather than optional extras: the first version of this function took
    only ``jobs`` and made the newest transcript the start page, so adding
    index pages without changing the signature would have left them
    written to disk and absent from the sidebar — published, unreachable,
    and looking finished.
    """
    by_campaign: dict[tuple, list] = defaultdict(list)
    for _src, dest, code, campaign_slug, month in jobs:
        by_campaign[(code, campaign_slug)].append((month, dest))

    if not jobs:
        # An empty instance still has to name a start page or Writerside
        # refuses to build, so emit nothing at all instead.
        return _HEADER.format(start="") + _FOOTER

    out = [_HEADER.format(start=master_index)]
    out.append(f'    <toc-element topic="{master_index}">\n')
    for (code, campaign_slug), months in sorted(by_campaign.items()):
        out.append(
            f'        <toc-element topic="{index_for(code, campaign_slug)}">\n')
        for _month, dest in sorted(months, reverse=True):
            out.append(f'            <toc-element topic="{dest}"/>\n')
        out.append("        </toc-element>\n")
    out.append("    </toc-element>\n")
    out.append(_FOOTER)
    return "".join(out)
