# 2026-08-10: Generates the card vocabulary and facts for BOTH the CUE and Pkl models from ONE
# API pull, so the two models can never disagree because they were fed different data.
#
# The vocabulary is a closed disjunction of real card names. That is what makes a typo impossible
# rather than merely reviewable: the original hand-written Crystron page shipped "Superior Dora"
# when the card is "Super Dora", and no amount of proofreading had caught it.
#
# Re-run after any decklist change. Output is generated - do not hand-edit cards.cue or Cards.pkl.
param(
  [string]$OutDir = $PSScriptRoot
)

$ErrorActionPreference = 'Stop'
$nl = [Environment]::NewLine

# Union of the Amelia-san and Yukinon decklists, plus cards those lists can search.
$names = @(
  # Crystron
  'Crystron Tristaros','Crystron Citree','Crystron Smiger','Crystron Thystvern',
  'Crystron Sulfefnir','Crystron Sulfador','Crystron Inclusion','Crystron Cluster',
  # Trains and machines
  'Night Train Blue Traveler','Scrap Recycler','Heavy Freight Train Derricrane',
  'Heavy Armored Knight Babeldecker','Flying Pegasus Railroad Stampede',
  'Therion "King" Regulus','Spell Canceller',
  # Spells and traps
  'Exceptional Schedule','Urgent Schedule','Special Schedule','Revolving Switchyard',
  'Foolish Burial','Called by the Grave','Crossout Designator','Triple Tactics Talent',
  'Forbidden Droplet','Barrage Blast',
  # Hand traps
  'Ash Blossom & Joyous Spring','Maxx "C"','Droll & Lock Bird','Mulcharmy Fuwalos',
  'Ghost Belle & Haunted Mansion','Nibiru, the Primal Being',
  # Extra deck
  'Crystron Eleskeletus','Crystron Quariongandrax','Centur-Ion Legatia','F.A. Dawn Dragster',
  'Infinitrack River Stormer','Cyber Dragon Nova','Cyber Dragon Infinity',
  'Superdreadnought Rail Cannon Gustav Max','Number 81: Superdreadnought Rail Cannon Super Dora',
  'Superdreadnought Rail Cannon Flying Launcher','Superdreadnought Rail Cannon Gustav Rocket',
  'Superdreadnought Rail Cannon Juggernaut Liebe','Divine Arsenal AA-ZEUS - Sky Thunder',
  'Clockwork Knight','Qliphort Genius','Double Headed Anger Knuckle','Ancient Gear Ballista'
)

function Get-Kind($t) {
  if ($t -match 'XYZ')     { return 'xyz' }
  if ($t -match 'Synchro') { return 'synchro' }
  if ($t -match 'Link')    { return 'link' }
  if ($t -match 'Monster') { return 'main' }
  if ($t -match 'Spell')   { return 'spell' }
  return 'trap'
}

$facts = @()
foreach ($n in $names) {
  $uri = 'https://db.ygoprodeck.com/api/v7/cardinfo.php?name=' + [uri]::EscapeDataString($n)
  $c = (Invoke-RestMethod -Uri $uri -TimeoutSec 30).data[0]
  if ($c.name -ne $n) { throw "NAME MISMATCH: asked '$n', got '$($c.name)'" }
  $lvl = 0
  if ($c.level)    { $lvl = $c.level }
  if ($c.linkval)  { $lvl = $c.linkval }
  $facts += [pscustomobject]@{
    name      = $c.name
    kind      = Get-Kind $c.type
    level     = $lvl
    tuner     = [bool]($c.type -match 'Tuner')
    race      = $c.race
    attribute = if ($c.attribute) { $c.attribute } else { 'NONE' }
  }
}

[System.IO.Directory]::CreateDirectory("$OutDir\cue") | Out-Null
[System.IO.Directory]::CreateDirectory("$OutDir\pkl") | Out-Null

function Esc($s) { return ($s -replace '\\','\\' -replace '"','\"') }

# ---- CUE ----
$vocab = ($facts | ForEach-Object { '"' + (Esc $_.name) + '"' }) -join ' | '
$rows = $facts | ForEach-Object {
  "`t" + '"' + (Esc $_.name) + '": {kind: "' + $_.kind + '", level: ' + $_.level +
  ', tuner: ' + $_.tuner.ToString().ToLower() + ', race: "' + $_.race + '", attribute: "' + $_.attribute + '"}'
}
$cue = @(
  '// GENERATED by gen-cards.ps1 from db.ygoprodeck.com. Do not hand-edit.',
  'package crystron',
  '',
  '#CardName: ' + $vocab,
  '',
  'cards: [#CardName]: #CardFacts',
  'cards: {',
  ($rows -join $nl),
  '}'
) -join $nl
[System.IO.File]::WriteAllText("$OutDir\cue\cards.cue", $cue)

# ---- Pkl ----
$pvocab = ($facts | ForEach-Object { '"' + (Esc $_.name) + '"' }) -join '|'
$prows = $facts | ForEach-Object {
  '  ["' + (Esc $_.name) + '"] { kind = "' + $_.kind + '"; level = ' + $_.level +
  '; tuner = ' + $_.tuner.ToString().ToLower() + '; race = "' + $_.race + '"; attribute = "' + $_.attribute + '" }'
}
$pkl = @(
  '// GENERATED by gen-cards.ps1 from db.ygoprodeck.com. Do not hand-edit.',
  'module crystron.Cards',
  '',
  'typealias CardName = ' + $pvocab,
  '',
  'class CardFacts {',
  '  kind: "main"|"synchro"|"xyz"|"link"|"spell"|"trap"',
  '  level: Int(this >= 0)',
  '  tuner: Boolean',
  '  race: String',
  '  attribute: String',
  '}',
  '',
  'cards: Mapping<CardName, CardFacts> = new {',
  ($prows -join $nl),
  '}'
) -join $nl
[System.IO.File]::WriteAllText("$OutDir\pkl\Cards.pkl", $pkl)

"generated $($facts.Count) cards -> cue\cards.cue and pkl\Cards.pkl"
