// GENERATED by gen-cards.ps1 from db.ygoprodeck.com. Do not hand-edit.
package crystron

#CardName: 
"Crystron Tristaros" | "Crystron Citree" | "Crystron Smiger" | "Crystron Thystvern" | "Crystron Sulfefnir" | "Crystron Sulfador" | "Crystron Inclusion" | "Crystron Cluster" | "Night Train Blue Traveler" | "Scrap Recycler" | "Heavy Freight Train Derricrane" | "Heavy Armored Knight Babeldecker" | "Flying Pegasus Railroad Stampede" | "Therion \"King\" Regulus" | "Spell Canceller" | "Exceptional Schedule" | "Urgent Schedule" | "Special Schedule" | "Revolving Switchyard" | "Foolish Burial" | "Called by the Grave" | "Crossout Designator" | "Triple Tactics Talent" | "Forbidden Droplet" | "Barrage Blast" | "Ash Blossom & Joyous Spring" | "Maxx \"C\"" | "Droll & Lock Bird" | "Mulcharmy Fuwalos" | "Ghost Belle & Haunted Mansion" | "Nibiru, the Primal Being" | "Crystron Eleskeletus" | "Crystron Quariongandrax" | "Centur-Ion Legatia" | "F.A. Dawn Dragster" | "Infinitrack River Stormer" | "Cyber Dragon Nova" | "Cyber Dragon Infinity" | "Superdreadnought Rail Cannon Gustav Max" | "Number 81: Superdreadnought Rail Cannon Super Dora" | "Superdreadnought Rail Cannon Flying Launcher" | "Superdreadnought Rail Cannon Gustav Rocket" | "Superdreadnought Rail Cannon Juggernaut Liebe" | "Divine Arsenal AA-ZEUS - Sky Thunder" | "Clockwork Knight" | "Qliphort Genius" | "Double Headed Anger Knuckle" | "Ancient Gear Ballista"

cards: [#CardName]: #CardFacts
cards: {
	"Crystron Tristaros": {kind: "main", level: 2, tuner: true, race: "Machine", attribute: "WATER"}
	"Crystron Citree": {kind: "main", level: 2, tuner: true, race: "Machine", attribute: "WATER"}
	"Crystron Smiger": {kind: "main", level: 3, tuner: false, race: "Machine", attribute: "WATER"}
	"Crystron Thystvern": {kind: "main", level: 3, tuner: false, race: "Machine", attribute: "WATER"}
	"Crystron Sulfefnir": {kind: "main", level: 5, tuner: false, race: "Machine", attribute: "WATER"}
	"Crystron Sulfador": {kind: "main", level: 5, tuner: false, race: "Machine", attribute: "WATER"}
	"Crystron Inclusion": {kind: "spell", level: 0, tuner: false, race: "Continuous", attribute: "NONE"}
	"Crystron Cluster": {kind: "trap", level: 0, tuner: false, race: "Continuous", attribute: "NONE"}
	"Night Train Blue Traveler": {kind: "main", level: 10, tuner: false, race: "Machine", attribute: "EARTH"}
	"Scrap Recycler": {kind: "main", level: 3, tuner: false, race: "Machine", attribute: "EARTH"}
	"Heavy Freight Train Derricrane": {kind: "main", level: 10, tuner: false, race: "Machine", attribute: "EARTH"}
	"Heavy Armored Knight Babeldecker": {kind: "main", level: 10, tuner: false, race: "Machine", attribute: "EARTH"}
	"Flying Pegasus Railroad Stampede": {kind: "main", level: 4, tuner: false, race: "Machine", attribute: "EARTH"}
	"Therion \"King\" Regulus": {kind: "main", level: 8, tuner: false, race: "Machine", attribute: "EARTH"}
	"Spell Canceller": {kind: "main", level: 5, tuner: false, race: "Machine", attribute: "WIND"}
	"Exceptional Schedule": {kind: "spell", level: 0, tuner: false, race: "Normal", attribute: "NONE"}
	"Urgent Schedule": {kind: "spell", level: 0, tuner: false, race: "Quick-Play", attribute: "NONE"}
	"Special Schedule": {kind: "spell", level: 0, tuner: false, race: "Normal", attribute: "NONE"}
	"Revolving Switchyard": {kind: "spell", level: 0, tuner: false, race: "Field", attribute: "NONE"}
	"Foolish Burial": {kind: "spell", level: 0, tuner: false, race: "Normal", attribute: "NONE"}
	"Called by the Grave": {kind: "spell", level: 0, tuner: false, race: "Quick-Play", attribute: "NONE"}
	"Crossout Designator": {kind: "spell", level: 0, tuner: false, race: "Quick-Play", attribute: "NONE"}
	"Triple Tactics Talent": {kind: "spell", level: 0, tuner: false, race: "Normal", attribute: "NONE"}
	"Forbidden Droplet": {kind: "spell", level: 0, tuner: false, race: "Quick-Play", attribute: "NONE"}
	"Barrage Blast": {kind: "trap", level: 0, tuner: false, race: "Continuous", attribute: "NONE"}
	"Ash Blossom & Joyous Spring": {kind: "main", level: 3, tuner: true, race: "Zombie", attribute: "FIRE"}
	"Maxx \"C\"": {kind: "main", level: 2, tuner: false, race: "Insect", attribute: "EARTH"}
	"Droll & Lock Bird": {kind: "main", level: 1, tuner: false, race: "Spellcaster", attribute: "WIND"}
	"Mulcharmy Fuwalos": {kind: "main", level: 4, tuner: false, race: "Winged Beast", attribute: "WIND"}
	"Ghost Belle & Haunted Mansion": {kind: "main", level: 3, tuner: true, race: "Zombie", attribute: "EARTH"}
	"Nibiru, the Primal Being": {kind: "main", level: 11, tuner: false, race: "Rock", attribute: "LIGHT"}
	"Crystron Eleskeletus": {kind: "synchro", level: 7, tuner: false, race: "Machine", attribute: "WATER"}
	"Crystron Quariongandrax": {kind: "synchro", level: 9, tuner: false, race: "Machine", attribute: "WATER"}
	"Centur-Ion Legatia": {kind: "synchro", level: 12, tuner: false, race: "Machine", attribute: "LIGHT"}
	"F.A. Dawn Dragster": {kind: "synchro", level: 7, tuner: false, race: "Machine", attribute: "LIGHT"}
	"Infinitrack River Stormer": {kind: "xyz", level: 5, tuner: false, race: "Machine", attribute: "EARTH"}
	"Cyber Dragon Nova": {kind: "xyz", level: 5, tuner: false, race: "Machine", attribute: "LIGHT"}
	"Cyber Dragon Infinity": {kind: "xyz", level: 6, tuner: false, race: "Machine", attribute: "LIGHT"}
	"Superdreadnought Rail Cannon Gustav Max": {kind: "xyz", level: 10, tuner: false, race: "Machine", attribute: "EARTH"}
	"Number 81: Superdreadnought Rail Cannon Super Dora": {kind: "xyz", level: 10, tuner: false, race: "Machine", attribute: "EARTH"}
	"Superdreadnought Rail Cannon Flying Launcher": {kind: "xyz", level: 10, tuner: false, race: "Machine", attribute: "EARTH"}
	"Superdreadnought Rail Cannon Gustav Rocket": {kind: "xyz", level: 10, tuner: false, race: "Machine", attribute: "EARTH"}
	"Superdreadnought Rail Cannon Juggernaut Liebe": {kind: "xyz", level: 11, tuner: false, race: "Machine", attribute: "EARTH"}
	"Divine Arsenal AA-ZEUS - Sky Thunder": {kind: "xyz", level: 12, tuner: false, race: "Machine", attribute: "LIGHT"}
	"Clockwork Knight": {kind: "link", level: 1, tuner: false, race: "Machine", attribute: "EARTH"}
	"Qliphort Genius": {kind: "link", level: 2, tuner: false, race: "Machine", attribute: "EARTH"}
	"Double Headed Anger Knuckle": {kind: "link", level: 2, tuner: false, race: "Machine", attribute: "EARTH"}
	"Ancient Gear Ballista": {kind: "link", level: 2, tuner: false, race: "Machine", attribute: "EARTH"}
}